# action.yml
name: 'Re:VIEW PDF generator'
description: 'build PDF of Re:VIEW and upload as artifact'
author: '@takahashim'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: 'green'
  icon: 'book'
